# Application
spring.application.name=fraud-detection-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/fraud_detection_dev?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Runs data.sql even for non-embedded databases
spring.sql.init.mode=always

# Server
server.port=8080

# Enable detailed error messages in responses (for development)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Fraud Service
fraud-service.base-url=http://localhost:8000
fraud-service.api-key=${FRAUD_SERVICE_API_KEY}

# Logging
logging.exception-conversion-word=%wEx{5}
logging.level.com.workshop.backend=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework=ERROR
logging.level.root=ERROR

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.max.block.ms=3000
spring.kafka.producer.properties.request.timeout.ms=3000
spring.kafka.producer.properties.delivery.timeout.ms=5000
spring.kafka.consumer.group-id=fraud-detection-backend
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*